INSERT INTO "PUBLIC"."REGION" VALUES ( 1, 'AS');
INSERT INTO "PUBLIC"."CONSTITUENCY" VALUES ( 1, 'Asturias',1 );
INSERT INTO "PUBLIC"."POLLING_PLACE" VALUES ( 1,1 );
INSERT INTO "PUBLIC"."CENSUS" VALUES (1,'sergio@gmail.com', 'Sergio', '9816446', 'sergio',1 );

